name: Test
on:
  release:
    types: [created]
# ‰ΩøÁî®Âπ∂ÂèëÂèñÊ∂à‰ªª‰ΩïÂΩìÂâç‰Ωú‰∏öÊàñËøêË°å
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  action_tigger:
    runs-on: ubuntu-latest
    steps:
      - name: Tag parse
        uses: AutumnWhj/tag-parse-action@master
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN }}

      - name: Checkout private repository
        uses: actions/checkout@master
        with:
          repository: threfo/${{ env.REPOSITORY }}
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ env.BRANCH }}
          
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: ${{ env.pusherName }} Ëß¶Âèë‰∫ÜÊûÑÂª∫ -- build
        run: yarn build --filePath="${{ env.BRANCH }}/default" --syncBranch="${{ env.syncBranch }}"

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYMMDDHHmm
          utcOffset: '+08:00'

      - name: Use current time
        env:
          F_TIME: '${{ steps.current-time.outputs.formattedTime }}'
        run: echo "NOW=$F_TIME" >> $GITHUB_ENV
      
      - name: Upload COS
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          args: upload -rs ./dist/ /${{ env.REPOSITORY }}/${{ env.syncBranch }}/default --ignore *.map
          secret_id: ${{ secrets.OSS_SECRET_ID }}
          secret_key: ${{ secrets.OSS_SECRET_KEY }}
          bucket: ${{ secrets.OSS_BUCKET }}
          region: ${{ secrets.OSS_REGION }}

      - name: Upload COS Backup release
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          args: upload -rs ./dist/ /${{ env.REPOSITORY }}/${{ env.syncBranch }}/${{ env.NOW }} --ignore *.map
          secret_id: ${{ secrets.OSS_SECRET_ID }}
          secret_key: ${{ secrets.OSS_SECRET_KEY }}
          bucket: ${{ secrets.OSS_BUCKET }}
          region: ${{ secrets.OSS_REGION }}

      - name: Sync privatisation project
        if: ${{ startsWith( env.syncBranch, 'release/') }}
        uses: AutumnWhj/sync-branches-action@master
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN }}
          headBranch: ${{ env.BRANCH }}
          syncBranches: ${{ env.syncBranch }}
          wechatKey: ${{ secrets.WORK_WECHAT_GITHUB_ROBOT_KEY }}

      - name: Notify WeChat Work success
        if: ${{ success() }}
        env:
          BOT_KEY: ${{ secrets.WORK_WECHAT_GITHUB_ROBOT_KEY }}
          POST_MESSAGE: üéâ È°πÁõÆ${{ env.REPOSITORY }}ÔºåÂàÜÊîØ${{ env.syncBranch }}ÊûÑÂª∫ÊàêÂäü„ÄÇ--- Github Actions
        uses: chhpt/wechat-work-messenger@v1.0.0

      - name: Notify WeChat Work failure
        if: ${{ failure() }}
        env:
          BOT_KEY: ${{ secrets.WORK_WECHAT_GITHUB_ROBOT_KEY }}
          POST_MESSAGE: ‚ùå È°πÁõÆ${{ env.REPOSITORY }}ÔºåÂàÜÊîØ${{ env.syncBranch }}ÊûÑÂª∫Â§±Ë¥•„ÄÇ--- Github Actions
        uses: chhpt/wechat-work-messenger@v1.0.0


